# Generated by Django 4.1.1 on 2022-09-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_addpost_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addpost",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
