# Generated by Django 4.1.1 on 2022-09-20 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_contact_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="post",
        ),
    ]
