# Generated by Django 4.1.1 on 2022-09-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addpost",
            name="desc",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="addpost",
            name="title",
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(max_length=100),
        ),
    ]
