# Generated by Django 4.1.1 on 2022-09-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_alter_addpost_desc_alter_addpost_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="addpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
