# Generated by Django 4.1.1 on 2022-09-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_alter_addpost_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addpost",
            name="desc",
            field=models.TextField(max_length=300),
        ),
    ]
