# Generated by Django 4.1.1 on 2022-09-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_alter_addpost_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="addpost",
            name="like",
            field=models.IntegerField(default=0),
        ),
    ]
