# Generated by Django 4.1.1 on 2022-09-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_addpost_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_on",
            field=models.DateField(auto_now_add=True),
        ),
    ]
