# Generated by Django 4.1.1 on 2022-09-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_alter_comment_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addpost",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
