# Generated by Django 4.1.1 on 2022-09-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_alter_addpost_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addpost",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
