# Generated by Django 4.1.1 on 2022-09-27 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0016_alter_addpost_options_remove_contact_subject_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="title",
        ),
        migrations.AlterField(
            model_name="addpost",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="add_post",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
