# Generated by Django 4.1.1 on 2022-09-28 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_remove_addpost_image_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="title",
            new_name="addpost",
        ),
    ]
