# Generated by Django 3.2.4 on 2022-10-13 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='addpost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='myapp.addpost'),
        ),
    ]
